const FLAGS: Record<string, string> = {
  'ARGENTINA':      '🇦🇷',
  'BRASIL':         '🇧🇷',
  'URUGUAY':        '🇺🇾',
  'FRANCE':         '🇫🇷',
  'FRANCIA':        '🇫🇷',
  'ALEMANIA':       '🇩🇪',
  'GERMANY':        '🇩🇪',
  'ESPAÑA':         '🇪🇸',
  'SPAIN':          '🇪🇸',
  'PORTUGAL':       '🇵🇹',
  'ITALIA':         '🇮🇹',
  'ITALY':          '🇮🇹',
  'INGLATERRA':     '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'ENGLAND':        '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'GALES':          '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'WALES':          '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'PAÍSES BAJOS':   '🇳🇱',
  'PAISES BAJOS':   '🇳🇱',
  'NETHERLANDS':    '🇳🇱',
  'HOLANDA':        '🇳🇱',
  'BÉLGICA':        '🇧🇪',
  'BELGICA':        '🇧🇪',
  'BELGIUM':        '🇧🇪',
  'CROACIA':        '🇭🇷',
  'CROATIA':        '🇭🇷',
  'SUIZA':          '🇨🇭',
  'SWITZERLAND':    '🇨🇭',
  'DINAMARCA':      '🇩🇰',
  'DENMARK':        '🇩🇰',
  'POLONIA':        '🇵🇱',
  'POLAND':         '🇵🇱',
  'SERBIA':         '🇷🇸',
  'MEXICO':         '🇲🇽',
  'MÉXICO':         '🇲🇽',
  'ESTADOS UNIDOS': '🇺🇸',
  'USA':            '🇺🇸',
  'CANADÁ':         '🇨🇦',
  'CANADA':         '🇨🇦',
  'ECUADOR':        '🇪🇨',
  'SENEGAL':        '🇸🇳',
  'MARRUECOS':      '🇲🇦',
  'MOROCCO':        '🇲🇦',
  'GHANA':          '🇬🇭',
  'CAMERÚN':        '🇨🇲',
  'CAMERUN':        '🇨🇲',
  'TÚNEZ':          '🇹🇳',
  'TUNEZ':          '🇹🇳',
  'TUNISIA':        '🇹🇳',
  'IRAN':           '🇮🇷',
  'IRÁN':           '🇮🇷',
  'ARABIA SAUDITA': '🇸🇦',
  'QATAR':          '🇶🇦',
  'JAPÓN':          '🇯🇵',
  'JAPON':          '🇯🇵',
  'JAPAN':          '🇯🇵',
  'COREA DEL SUR':  '🇰🇷',
  'KOREA':          '🇰🇷',
  'AUSTRALIA':      '🇦🇺',
  'COSTA RICA':     '🇨🇷',
  'COLOMBIA':       '🇨🇴',
  'CHILE':          '🇨🇱',
  'PERU':           '🇵🇪',
  'PERÚ':           '🇵🇪',
  'BOLIVIA':        '🇧🇴',
  'PARAGUAY':       '🇵🇾',
  'VENEZUELA':      '🇻🇪',
}

export function teamFlag(name: string): string {
  return FLAGS[name.toUpperCase().trim()] ?? ''
}
