const FLAGS: Record<string, string> = {
  // Sudamérica
  'ARGENTINA':      '🇦🇷',
  'BRASIL':         '🇧🇷',
  'BRAZIL':         '🇧🇷',
  'URUGUAY':        '🇺🇾',
  'COLOMBIA':       '🇨🇴',
  'CHILE':          '🇨🇱',
  'PERU':           '🇵🇪',
  'PERÚ':           '🇵🇪',
  'BOLIVIA':        '🇧🇴',
  'PARAGUAY':       '🇵🇾',
  'VENEZUELA':      '🇻🇪',
  'ECUADOR':        '🇪🇨',

  // Europa
  'FRANCE':         '🇫🇷',
  'FRANCIA':        '🇫🇷',
  'ALEMANIA':       '🇩🇪',
  'GERMANY':        '🇩🇪',
  'ESPAÑA':         '🇪🇸',
  'SPAIN':          '🇪🇸',
  'PORTUGAL':       '🇵🇹',
  'ITALIA':         '🇮🇹',
  'ITALY':          '🇮🇹',
  'INGLATERRA':     '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'ENGLAND':        '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'GALES':          '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'WALES':          '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'ESCOCIA':        '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'SCOTLAND':       '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'PAÍSES BAJOS':   '🇳🇱',
  'PAISES BAJOS':   '🇳🇱',
  'NETHERLANDS':    '🇳🇱',
  'HOLANDA':        '🇳🇱',
  'BÉLGICA':        '🇧🇪',
  'BELGICA':        '🇧🇪',
  'BELGIUM':        '🇧🇪',
  'CROACIA':        '🇭🇷',
  'CROATIA':        '🇭🇷',
  'SUIZA':          '🇨🇭',
  'SWITZERLAND':    '🇨🇭',
  'DINAMARCA':      '🇩🇰',
  'DENMARK':        '🇩🇰',
  'POLONIA':        '🇵🇱',
  'POLAND':         '🇵🇱',
  'SERBIA':         '🇷🇸',
  'AUSTRIA':        '🇦🇹',
  'SUECIA':         '🇸🇪',
  'SWEDEN':         '🇸🇪',
  'NORUEGA':        '🇳🇴',
  'NORWAY':         '🇳🇴',
  'TURQUÍA':        '🇹🇷',
  'TURQUIA':        '🇹🇷',
  'TURKEY':         '🇹🇷',
  'REPÚBLICA CHECA':'🇨🇿',
  'REPUBLICA CHECA':'🇨🇿',
  'CZECH REPUBLIC': '🇨🇿',
  'HUNGRÍA':        '🇭🇺',
  'HUNGRIA':        '🇭🇺',
  'HUNGARY':        '🇭🇺',
  'RUMANIA':        '🇷🇴',
  'ROMANIA':        '🇷🇴',
  'ESLOVAQUIA':     '🇸🇰',
  'SLOVAKIA':       '🇸🇰',
  'GRECIA':         '🇬🇷',
  'GREECE':         '🇬🇷',
  'ALBANIA':        '🇦🇱',
  'ESLOVENIA':      '🇸🇮',
  'SLOVENIA':       '🇸🇮',
  'UCRANIA':        '🇺🇦',
  'UKRAINE':        '🇺🇦',
  'BOSNIA HERZEGOVINA': '🇧🇦',
  'BOSNIA Y HERZEGOVINA': '🇧🇦',

  // Norteamérica / CONCACAF
  'ESTADOS UNIDOS': '🇺🇸',
  'USA':            '🇺🇸',
  'CANADÁ':         '🇨🇦',
  'CANADA':         '🇨🇦',
  'MEXICO':         '🇲🇽',
  'MÉXICO':         '🇲🇽',
  'COSTA RICA':     '🇨🇷',
  'JAMAICA':        '🇯🇲',
  'PANAMÁ':         '🇵🇦',
  'PANAMA':         '🇵🇦',
  'HONDURAS':       '🇭🇳',
  'HAITÍ':          '🇭🇹',
  'HAITI':          '🇭🇹',
  'CURAZAO':        '🇨🇼',
  'CURACAO':        '🇨🇼',

  // África
  'SENEGAL':        '🇸🇳',
  'MARRUECOS':      '🇲🇦',
  'MOROCCO':        '🇲🇦',
  'GHANA':          '🇬🇭',
  'CAMERÚN':        '🇨🇲',
  'CAMERUN':        '🇨🇲',
  'TÚNEZ':          '🇹🇳',
  'TUNEZ':          '🇹🇳',
  'TUNISIA':        '🇹🇳',
  'NIGERIA':        '🇳🇬',
  'EGIPTO':         '🇪🇬',
  'EGYPT':          '🇪🇬',
  'COSTA DE MARFIL':'🇨🇮',
  'IVORY COAST':    '🇨🇮',
  'ARGELIA':        '🇩🇿',
  'ALGERIA':        '🇩🇿',
  'SUDÁFRICA':      '🇿🇦',
  'SUDAFRICA':      '🇿🇦',
  'SOUTH AFRICA':   '🇿🇦',
  'CABO VERDE':     '🇨🇻',
  'CAPE VERDE':     '🇨🇻',
  'CONGO':          '🇨🇩',
  'DR CONGO':       '🇨🇩',
  'RD CONGO':       '🇨🇩',

  // Asia / Medio Oriente
  'IRAN':           '🇮🇷',
  'IRÁN':           '🇮🇷',
  'ARABIA SAUDITA': '🇸🇦',
  'SAUDI ARABIA':   '🇸🇦',
  'QATAR':          '🇶🇦',
  'JAPÓN':          '🇯🇵',
  'JAPON':          '🇯🇵',
  'JAPAN':          '🇯🇵',
  'COREA DEL SUR':  '🇰🇷',
  'SOUTH KOREA':    '🇰🇷',
  'KOREA':          '🇰🇷',
  'AUSTRALIA':      '🇦🇺',
  'IRAQ':           '🇮🇶',
  'IRAK':           '🇮🇶',
  'JORDANIA':       '🇯🇴',
  'JORDAN':         '🇯🇴',
  'UZBEKISTÁN':     '🇺🇿',
  'UZBEKISTAN':     '🇺🇿',
  'NUEVA ZELANDA':  '🇳🇿',
  'NEW ZEALAND':    '🇳🇿',
}

export function teamFlag(name: string): string {
  return FLAGS[name.toUpperCase().trim()] ?? ''
}
